
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-es-http-external
  namespace: je-ns-dev
spec:
  type: ExternalName
  externalName: elasticsearch-es-http.elasticsearch.svc.cluster.local 


